import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
export const ItemCategory = v.union(
    v.literal("wallet"),
    v.literal("phone"),
    v.literal("keys"),
    v.literal("bag"),
    v.literal("documents"),
    v.literal("electronics"),
    v.literal("jewelry"),
    v.literal("clothing"),
    v.literal("id_card"),
    v.literal("cash"),
    v.literal("other")
);


export default defineSchema({
    listings: defineTable({
        // item details
        title: v.string(),
        description: v.string(),
        images: v.array(v.id("_storage")),

        type: v.union(v.literal("lost"), v.literal("found")),
        categories: v.array(ItemCategory),

        color: v.optional(v.string()),
        brand: v.optional(v.string()),

        // location
        locationName: v.string(),
        latitude: v.optional(v.number()),
        longitude: v.optional(v.number()),

        // lifecycle
        status: v.union(
            v.literal("open"),
            v.literal("matched"),
            v.literal("resolved")
        ),

        // Clerk user reference
        clerkUserId: v.string(),

        // Search field
        searchText: v.string(),

        // Vector embedding for semantic matching (768 dimensions from Gemini)
        embedding: v.optional(v.array(v.float64())),

        createdAt: v.number(),
        updatedAt: v.number(),
    })
        .index("by_type", ["type"])
        .index("by_user", ["clerkUserId"])
        .index("by_status", ["status"])
        .searchIndex("search_text", {
            searchField: "searchText",
            filterFields: ["status", "type"],
        })
        .index("by_category", ["categories"])
        .vectorIndex("by_embedding", {
            vectorField: "embedding",
            dimensions: 768,
            filterFields: ["type", "status"],
        }),
    matches: defineTable({
        lostListingId: v.id("listings"),
        foundListingId: v.id("listings"),

        score: v.number(),

        status: v.union(
            v.literal("suggested"),
            v.literal("confirmed"),
            v.literal("rejected")
        ),

        createdAt: v.number(),
    })
        .index("by_lost", ["lostListingId"])
        .index("by_found", ["foundListingId"]),

    conversations: defineTable({
        listingId: v.id("listings"),
        participantIds: v.array(v.string()),
        lastMessage: v.optional(v.string()),
        lastMessageAt: v.optional(v.number()),
        createdAt: v.number(),
    }).index("by_listing", ["listingId"]),

    messages: defineTable({
        conversationId: v.id("conversations"),
        senderClerkUserId: v.string(),
        senderName: v.optional(v.string()),
        isRead: v.boolean(),
        content: v.string(),
        createdAt: v.number(),
    }).index("by_conversation", ["conversationId"]),

    verificationClaims: defineTable({
        listingId: v.id("listings"),
        claimantClerkUserId: v.string(),

        // Questions generated by AI, including the correct answer
        generatedQuestions: v.optional(v.array(v.object({
            question: v.string(),
            options: v.array(v.string()), // A, B, C, D
            correctIndex: v.number(), // 0-3
        }))),

        // Answers submitted by the user
        answers: v.optional(v.array(
            v.object({
                question: v.string(),
                answerIndex: v.number(),
            })
        )),

        status: v.union(
            v.literal("pending"), // Initial request by claimant
            v.literal("generating"), // Approved by finder, generating questions
            v.literal("questions_generated"), // AI has generated questions
            v.literal("approved"), // Successfully answered
            v.literal("rejected"), // Incorrect answers or rejected by finder
            v.literal("failed") // Too many attempts (optional, or just rejected)
        ),

        createdAt: v.number(),
        reviewedAt: v.optional(v.number()),
    }).index("by_listing", ["listingId"]),

    complaints: defineTable({
        title: v.string(),
        description: v.string(),
        category: v.union(
            v.literal("abuse"),
            v.literal("spam"),
            v.literal("inappropriate_content"),
            v.literal("harassment"),
            v.literal("other")
        ),

        // User who filed the complaint
        clerkUserId: v.string(),

        // Optional reference to the listing being reported
        listingId: v.optional(v.id("listings")),

        // Evidence files (screenshots, etc.)
        evidence: v.array(v.id("_storage")),

        // Complaint status
        status: v.union(
            v.literal("open"),
            v.literal("in-review"),
            v.literal("resolved"),
            v.literal("closed")
        ),

        // Admin moderation
        adminNotes: v.optional(v.string()),
        reviewedBy: v.optional(v.string()), // Clerk user ID of admin

        createdAt: v.number(),
        updatedAt: v.number(),
        reviewedAt: v.optional(v.number()),
    })
        .index("by_user", ["clerkUserId"])
        .index("by_listing", ["listingId"])
        .index("by_status", ["status"])
        .index("by_category", ["category"]),
});