"use client";

import { motion } from "framer-motion";
import { Search, ShieldCheck, MessageCircle, HeartHandshake } from "lucide-react";

export default function HowItWorksPage() {
    const steps = [
        {
            title: "Report",
            description: "Whether you've lost an item or found one, start by creating a detailed report. Upload images and provide a description.",
            icon: Search,
            color: "bg-blue-500"
        },
        {
            title: "Match",
            description: "Our AI constantly scans the database. When it finds a high-confidence match between a lost and found item, you get notified.",
            icon: HeartHandshake,
            color: "bg-purple-500"
        },
        {
            title: "Verify",
            description: "To prevent fraud, the claimant must answer security questions generated by AI based on hidden details of the found item.",
            icon: ShieldCheck,
            color: "bg-teal-500"
        },
        {
            title: "Connect",
            description: "Once verified, a secure chat opens up. Coordinate a safe meeting place or delivery to reunite the item with its owner.",
            icon: MessageCircle,
            color: "bg-orange-500"
        }
    ];

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-24 px-4">
            <div className="max-w-5xl mx-auto">
                <div className="text-center mb-16">
                    <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white mb-4">How Rubix Works</h1>
                    <p className="text-xl text-slate-500 dark:text-slate-400">Allowed simplicity, powered by intelligence.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                    {steps.map((step, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: index * 0.1 }}
                            className="bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 relative overflow-hidden group hover:shadow-md transition-all"
                        >
                            <div className={`absolute top-0 left-0 w-full h-1 ${step.color}`} />
                            <div className={`w-12 h-12 ${step.color} rounded-xl flex items-center justify-center mb-6 text-white shadow-lg`}>
                                <step.icon className="w-6 h-6" />
                            </div>
                            <h3 className="text-xl font-bold mb-3 dark:text-white">{step.title}</h3>
                            <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
                                {step.description}
                            </p>
                        </motion.div>
                    ))}
                </div>
            </div>
        </div>
    );
}
